#
# buildspec.yml
#

version: 0.2

#env:
#  variables:
#    name: value

phases:
  install:
    runtime-versions:
      nodejs: 10
#    commands:

  pre_build:
    commands:
      - BUILD_VERSION=$(date --date="@$(echo $CODEBUILD_START_TIME | cut -c1-10)" +"%Y%m%d%H%M%S")
      - COMMIT_TAG=gitcommit-$CODEBUILD_RESOLVED_SOURCE_VERSION

  build:
    commands:
      - npm install
      - npx bower install --allow-root
      - npm run build
      - BUILD_TARFILE=$CODEBUILD_SRC_DIR/$BUILD_VERSION-es6-assets.tgz
      - cd build/es6-unbundled
      - tar czvf $BUILD_TARFILE .
      - aws s3 cp $BUILD_TARFILE s3://$BUCKET_NAME
      #- rsync -av build/es6-unbundled/ <target host>:/wwwstatic

#  post_build:
#    commands:

#
# end of file
#
