#
# buildspec.yml
#

version: 0.2

env:
  variables:
    drupal_host: drupal.lib.virginia.edu
    drupal_user: bamboo
    drupal_key: build-deploy-scripts/keys/bamboo_deploy

phases:
  install:
    runtime-versions:
      nodejs: 10
#    commands:

  pre_build:
    commands:
      - BUILD_VERSION=$(date --date="@$(echo $CODEBUILD_START_TIME | cut -c1-10)" +"%Y%m%d%H%M%S")
      - COMMIT_TAG=gitcommit-$CODEBUILD_RESOLVED_SOURCE_VERSION
      - git clone https://$GITLAB_USER:$GITLAB_TOKEN@gitlab.com/uvalib/build-deploy-scripts.git

  build:
    commands:
      - npm install
      - npx bower install --allow-root
      - npm run build
      - chmod 600 $CODEBUILD_SRC_DIR/$drupal_key
      - scp -r -C -oStrictHostKeyChecking=accept-new -i $CODEBUILD_SRC_DIR/$drupal_key $drupal_user@$drupal_host:/usr/share/drupal/sites/default/files/ .
      - node ./imagemin-files.js
      - rsync -avh files-ready/ files
      - BUILD_TARFILE=$CODEBUILD_SRC_DIR/$BUILD_VERSION-assets.tgz
      - tar czvf $BUILD_TARFILE build/es6-unbundled data/pages files
      - aws s3 cp $BUILD_TARFILE s3://$BUCKET_NAME --quiet

#  post_build:
#    commands:

#
# end of file
#
