#
# buildspec.yml
#

version: 0.2

#env:
#  variables:
#    name: value

phases:
  install:
    runtime-versions:
      nodejs: 12
#    commands:

  pre_build:
    commands:
      - npm install --global yarn

  build:
    commands:
      - cd packages/main-web-site
      - yarn install
      - npx @11ty/eleventy
      - cd _site
      - aws s3 sync . s3://$BUCKET_NAME
      - aws cloudfront create-invalidation --distribution-id $CDN_ID --paths "/*"

#  post_build:
#    commands:

#
# end of file
#
